### PR TITLE
Short-circuit some index writes

### PR DESCRIPTION
**Pull request by zobar**
* will not attempt to delete old index entries for a new record (because they wouldn't exist)
* will not update index entries if indexed attributes haven't changed (because the index entries wouldn't change either)
* will not read/write index entries for composite index if all attributes are nil (same behavior as non-composite index)
* Issues atomic updates to save and delete index entries, rather than a read followed by a save

### CODE REVIEW

**Comment by tomharris** [comment]
Nice :+1:

**Comment by tranqy** [comment]
awesome.. +1

**Comment by fuzz** [comment]
mi0001345701

**Comment by wclark** [comment]
Wow.  +10 for effort.

**Pull request closed without merging**
